uint8 BUTTON_START=1   #0x01
uint8 BUTTON_1=2       #0x02
uint8 BUTTON_2=3       #0x03
uint8 BUTTON_3=4       #0x04
uint8 BUTTON_SPOT=5    #0x05
uint8 BUTTON_CAREFUL=6 #0x06
uint8 BUTTON_UP=7      #0x07
uint8 BUTTON_LEFT=8    #0x08
uint8 BUTTON_RIGHT=9   #0x09
uint8 BUTTON_HOME=10   #0x0a
uint8 BUTTON_REPORT=11 #0x0b

uint8 BUOY_LEFT=21         
uint8 BUOY_CENTER_LEFT=22  
uint8 BUOY_CENTER=23       
uint8 BUOY_CENTER_RIGHT=24 
uint8 BUOY_RIGHT=25        

Header header
uint8 omni
uint8 left
uint8 right
uint8 center

